Meteor.subscribe("games")
Meteor.subscribe("players")
Meteor.subscribe("rounds")
//Meteor.subscribe('blacks')
//Meteor.subscribe('whites')  
Meteor.subscribe('playersOwnWhites')  
Meteor.subscribe('playersSelectedWhites')  